output_dir: data/models/training/OFA-base+mix_curriculum

model:
  model_module: OFAModuleCurriculum4
  ckpt_dir: data/checkpoints/huggingface/OFA-base
  resume_from_checkpoint: data/models/training/OFA-base+mix_curriculum/version_3/checkpoints/final-checkpoint.ckpt

vocab:
  code_vocab_size: 8192 # img token vocab size
  loc_vocab_size: 1000 # location token vocab size
  extra_space_vocab_size: 38 # extra space for code tokenization vocab size

data:
  data_module: Curriculum4RelationDataModule
  batch_size: 1
  num_workers: 8


classifyImage:
  data:
    data_module: ClassifyImageNetDataModule
    dataset_img_dir: data/imagenet21k_resized/imagenet21k_train/
    dataset_dir: ImageCode/
    max_position_embeddings: 1024 # from model.config
    code_file: buffer_claasification_imagenet21k.json




detection_coco:
  data:
    data_module: DetectionCocoDataModule
    dataset_dir: ImageCode/
    dataset_img_dir: data/COCO/train2017/
    max_position_embeddings: 1024 # from model.config
    mask:
        object_mask_prob: 0.5
        pos_mask_ratio: 0.75
    code_file: buffer_detection_COCO.json


detection_object365:
  data:
    data_module: DetectionObject365DataModule
    dataset_dir: ImageCode/
    dataset_img_dir: data/object365/
    max_position_embeddings: 1024 # from model.config
    mask:
        object_mask_prob: 0.5
        pos_mask_ratio: 0.75
    code_file: buffer_detection_object365.json

detection_openimages:
  data:
    data_module: DetectionOpenimagesDataModule
    dataset_dir: ImageCode/
    dataset_img_dir: data/OpenImage/
    max_position_embeddings: 1024 # from model.config
    mask:
      object_mask_prob: 0.5
      pos_mask_ratio: 0.75
    code_file: buffer_detection_openimages.json








attribute_LSA:
  data:
    data_module: AttributeLSADataModule
    dataset_dir: ImageCode/
    dataset_img_dir: data/
    max_position_embeddings: 1024 # from model.config
    mask:
      attribute_mask_prob: 0.75
      object_mask_prob: 0.5
      pos_mask_ratio: 0.75
    code_file: buffer_attribute_LSA.json


scenegraphopenimage:
  data:
    data_module: SceneGraphOpenimagesDataModule
    dataset_dir: ImageCode/
    dataset_img_dir: data/OpenImage
    max_position_embeddings: 1024 # from model.config
    mask:
      object_mask_prob: 0.15
      pos_mask_ratio: 0.75


scenegraphVG:
  data:
    data_module: SceneGraphVGDataModule
    dataset_dir: ImageCode/
    dataset_img_dir: data/Images
    max_position_embeddings: 1024 # from model.config
    mask:
      object_mask_prob: 0.15
      pos_mask_ratio: 0.75
      attribute_mask_ratio: 0.5
      relation_mask_ratio: 0.5
      relation_object_mask_ratio: 0.5






training:
  max_epochs: 14
  optimizer:
    lr: 1.e-4
    weight_decay: 1.e-2
  precision: 16
  # save checkpoint every n optimization steps (actual_step / accumulate_grad_batches)
  checkpoint_every_n_steps: 10000 # approx 1 hr
  # OFA originally use 2048 batchsize
  accumulate_grad_batches: 256 # 2048/(2*4)=256
